apiVersion: v1
kind: Secret
metadata:
    name: authelia
stringData:
    JWT_TOKEN: ENC[AES256_GCM,data:1C0JEcmgqeLJCguTaFrxUxv9YBVbxHZ3vo57L+9zJUp0jClxjnDbm01+lAmfqe2kFvqPpNKEdAMT494oXgblifnqo98ztd5gqHKKOGhNbVMjIHWPuL+uAnznU5MSWQwX+oxCrry43JEOIclHVtIApGGMmbBAZ3kCRU64LeRN2co=,iv:/LyI5A0ILbd3tc5DUeu8ESMImWG8Edpb76cbj37jfrw=,tag:sIP3SPqP9ZhRVy8mRBbWHQ==,type:str]
    SESSION_ENCRYPTION_KEY: ENC[AES256_GCM,data:/edc8e6ZkdeBCXnbiGgutZ8FxuCR2JuB6z1DN3jEI9d4jSSS2okSqHUBpH/imLwnNpeYSCy/6SMb+RQQqDAt0kto5lV2Pu3USNBGj4UI3x1dp5a+VNuUQo6a4DHrOYJ/a+qI46R40dhbYBNKs7KcefxiKilBMKfECPFUz0Z1VTk=,iv:vKxOTrw+MEX0oepo0xJST/D4m7gpYBO1Qh3PuR368nU=,tag:Gc32A8I2Ky6sO5iK2Ahpjw==,type:str]
    STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:f+MTxN4LwFv3iB+A1ElZQAAoIxACiCJ6om3ZuqCeM2PJmjzXwa5RquikGHaznDjr7fT4sHaJGEKnSDYECV12TN4/Co6hCdlWbaQQWGOenP0W+wctsb2EEgL+ZdyTovh5S816qsHhzlQAcByeU6ToBpIKOU/xuLT4kazA6wGmFNU=,iv:mTX3ahKxMK28HZGS1N31SR1hk4+KUs8sSWixj4GvH6w=,tag:5sDRfEt5E0UL+wQktOgxIg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:SgXKtpSJSDI/1KAicmEnCCblyw6VEe0tgpp5rvDgmDZKQuBQSwvhF2oJHMCg+E4/4LQbJ6muA+SW99kNInkEQLz/42dBFOvZHFIzZ+aTV5p9ymeLklQqFm1N3mdTxmoGmIEXSbV/8R/YkuA3pnLzGdnKWgKf16qUTxlzKmRvKeo=,iv:WxkqemLS8+V6dA6hIISVunKoeD111YFvL8DDb3Wy61c=,tag:jnhRzHsyhBMrXojOq+qiNQ==,type:str]
    STORAGE_PASSWORD: ENC[AES256_GCM,data:GDyxI66WX4XpdlUfjHFGfG7pKdZDdwkh5fTPdalB3emFScUGVxv6eZQlnhgzjJgWEHHOB/QKhYQhsZy55pqIRK3Ns08qI6+vtKsRduVRbSQpwpoV2s54cKMKZUrcbMcNVRl9M9pPsufrDP62TuDod7ga/Va1RFlTVsir/BwT4ag=,iv:zWdyCHi/ck72+S6F45JU3C1LpvSqoXePjO1XseXS8hw=,tag:HyY6rVyL37vqtuR060Y61A==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:KHC5cvxCCbtO5CxLQ8FyYu5D,iv:rzXBDSdFQ3WXDYPRbN5yn9ce8CZVIbcHEX1jCqQOSDM=,tag:c2T8bBXtbXhXk7jbtgPHyQ==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:o5jyJSerPRcm//xwRDFRJff13SYT,iv:B/5dB5vhyWOkArOWxS7BZiwx5cQGmQGqpvtLK1CXJ5c=,tag:AxQLT54iVGXdUg4aB6EELw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140ydupaur7u5frpf2229zz73xwfg6ndpuwn27lna425y8t44ucfs07ahf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArY3BxTy9ZdFBHMXNtUUNj
            Rk8yQ1VSY1JDTnYrS3k4cE9uaXpPS2lCNFI4Clh2L3FBeURKdEs5ZjhoS3hzVk9P
            aXUyWkNUQVBUSy9YQm9pQkF1SEh3djgKLS0tIDNSb0I0UDE2aDJtUW03Z1NQTGdx
            NjRGZ1RCWFg5T0hoS0hsTjFyS0RFUzAK/OOuFq9YOonvSTgVbqiE1yp/DstIvRW4
            eJUfaNBXCJgcBiq76hJQ5+B0Vn+j5Dz9yj2cuGfaYMtx9Q1ZSzIyfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-21T18:11:47Z"
    mac: ENC[AES256_GCM,data:DXJAt0U8iWUIfDsLaJ02oAwO81nDZjRHazyPFAHFWh3BnqqzSsPgRJXculjbVLtVjPU5O/gcp8aEMLp/TtvtYWIFu0XsiXTI3m8pHk6LtmZTiXvMwOiCCGiIE9uDxpTMlSAdv9XJI3DWHBwbmF8rnvqfT1CC9P1yWALbTvMdinc=,iv:zHhT6VqNk1XJl6wJc6HuH4+7Bfc76lQY56WetKZ4vD4=,tag:FV7X7l5sw1YaYWbsg3Iy/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
