apiVersion: v1
kind: Secret
metadata:
    name: authelia
stringData:
    JWT_TOKEN: ENC[AES256_GCM,data:vg+AHGNJ2dGT1bAuN2NJqzziiSG/ZoU/,iv:U5xf49dfE7u+k4QmGxQpB+uRp55oFBFiyUq8ceArUHc=,tag:Mj5qfWRNIShZEaZE5U7eFQ==,type:str]
    SESSION_ENCRYPTION_KEY: ENC[AES256_GCM,data:8CGplpZ5IOk+MWiQAXPY+Qh1FlSsfEenBtNg72mZyILwCdoJ1vxFDXQOcR1i27rRN76wizymSSjCNb1Q8ObomFORYHy3YSqDGnnWEvJ0QJ/Zn/2WkP6bXbM+nwK3flOEKZ4Smo4Fqpm2oQLyeq1ym4HCRSl08/wZt9pG95+25lo=,iv:rI1+u84Zh4+zYRIvqQrAJZLTOOpt9RX7PP32NLRjcFI=,tag:edpMf+evUuI0FEfny2ixtQ==,type:str]
    STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:5Fa/uDOuv9dlB1DuaZ5lbTurlzNC1mqeLr0Uu8i6iY2hb3jTj90JJaq1RTsd3uEp2ElEBhYy09K9vOBBkCkwYMZE8HI+hatnCnelCOQiuRFgHgjathdb/43WBJLAr9kFHaz06j70cFXEJNK1G+MePf9EZFc81gfiMN4EUjaThkc=,iv:+jZtO90EXyFbouJsKBARwMgBPRoSO0+dJOZyV/3Xy4E=,tag:IG7uy1h1Zva1/hJFVcPfpw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:qg0VWgdW5DO6UocQB/9/KIJIsKQ=,iv:8gmJnqqbH38n4iKjotM+1yyfk8PxuB2FOujj4x5Bhu8=,tag:sloVD84Xhm7TosjoaAA2KA==,type:str]
    STORAGE_PASSWORD: ENC[AES256_GCM,data:EVCULXEj/nvoBQFiYZ8ZUTS3zielFWU6EnVSE4GKHwQbftHEondvu2ZBTnx8aCCZLGCW/n0+At9G9UmooVBrif9iXGO3fJuny28krpRn8a7wdVs7vDFn2mTIvvhRAhhCun1a2tBNavnzPK+WdsvmRAoOGClk5JD8FSXSfVYREhk=,iv:tmGMVs9maIyg9v1tVAaLPZpIgYu4fUi7Egrm6H7Ed+o=,tag:vWL26L7cZxBq57/rwWWH7A==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:ify40GeMPwKES3RMk0e9Ljm7,iv:YE7ATLUIO2z4CFvvuKq/+kgfz/aNQM1CEKQYVVpYsXA=,tag:EQvNDmI9Ard4nJhDbFiGng==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:n/pSPgy2QfEICojq3qyZCNUhNz62,iv:vKEjwZ96+uLnwsQRDaOUnSPptdjKQ5LdHZsFgaqwFIo=,tag:FFMZIDr29IqKzsxqGb+ZKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140ydupaur7u5frpf2229zz73xwfg6ndpuwn27lna425y8t44ucfs07ahf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQjRDak41NCtvVDlXRXhr
            Z0owVi8wMzhGRjJFWlgrWW8yM1I3Q20zR2trCnNsb1huZElZMEhrUFlBY3VMSkFN
            TDljNk5aQ21reWYzOG9OaDIxa2wwNk0KLS0tIHpCQ2FrZEMzK1FPTmdER2k0V2Zp
            WDVCeHpSVjUxQytCMERNb1BiUzNhUHMKTF3tsa8if8n2vIq/arnt8N1Ekgzktl4t
            MTZGK0v8gxfgfrXZzzWtUfqtWQLgHu49MXiIrV64EDj7IrLvo8tpaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-20T20:42:26Z"
    mac: ENC[AES256_GCM,data:MwOTeXvHNSivJeN/1dF20jORo+7+AxC1icf4v6c2ZGeWiAbzFY/hfXz3SuQvj41L0pMwZ+mcC7IVPYtKfrWsyYikq88SjWVo6qQ9OKAhNJVMP5YffCXhaTZVHB9YHVVeCjL/Ck3X/0Bxfyoh/f6XoOsdl8REIz1izfcOKd60GAU=,iv:pFJTW//0OAepCTGMD7UpUVmRXGTYtzXDituPdXMUyEE=,tag:MTJlsyKEttGmzbFCXBQEMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
