---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-postgresql-datastore
spec:
  storageClassName: longhorn-backup
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
      