apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
stringData:
    admin-user: ENC[AES256_GCM,data:T5I4qgmID2o5,iv:/OYYLtHgHn73Knabtjrbbfn/IdG0wN8hK2ktoXFEn6U=,tag:wwphg+8gkq4KanGsnwNyTw==,type:str]
    admin-password: ENC[AES256_GCM,data:L5exTM5+60EnUQbfg62S,iv:uCEowEGxXJaZ6K5Yw2//SQ55g+AmhUMOv1F+3ovGLL8=,tag:qlcA9Q8cf5C3D7OAteSJXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140ydupaur7u5frpf2229zz73xwfg6ndpuwn27lna425y8t44ucfs07ahf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0U2I5UFE3VW0xRHUvWlFu
            MVdYWDBNd0hFaDVtQWdxMEFRSWpyelFpc3pjCkluYlpObFdXb1dmRnJjZDE0NzdY
            eTRiR09jbGlSM2w3d3lxbllVdE9lVGMKLS0tIFNjeGtaSGVnUHlXMmd2dU40V2Fa
            STU2MjA4aG53NVVLcHdUbDdFNlZwNXMK5pDWNgJ7E0i83t5H3i1pv0klpXdrrFLV
            SWM94apUOy6oZqFQuWqVgMvX4P73QknLBzQzeYNt3I8IuPtKapt0Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-14T17:55:56Z"
    mac: ENC[AES256_GCM,data:264eCEw0BjrzDBBI2vK0Vc4QnWmakOsNwhGB4JoyOdclxutlYHmukxyzgSe9K0EkKN77UjoOl6S5fJLhI1/rLbb8e9esd1RYlp22RkceB4VlSjEOEgVGS4PBCP/9F9IujDYdCSCEnaERTo+pInyp6EFZPtzRK3EA0RB6QHP9Hi4=,iv:hmys3xZ0CWKtJ4yoLuXnP3LtaBeBwNjTn9uqnI5vf5w=,tag:LNIMp8wGm6ND4pdu5U97Wg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
