apiVersion: v1
data:
    age.agekey: ENC[AES256_GCM,data:s7lwkRkTLalmmIVoV3oec6AQFAbuCA76qrNa2tJeG7vOgyqCK6n+qYe4i+ILGYorn1IPN/zgKOLytRDwWW/grtowoUVvmw1e+9a/jhAyKM9cNLlmUvH5PM3QzInqXznopndZHVkdiNKkLTt4e/xJVzn9O+S+vGRLhP28psCYWsZ272fm2YFtTnptaO5L8H36mtU73YGSy5V77uREtBPXd3ZsNsN+WNps3eOJZ4T+nqMU2pEIyJj+BlJRcaUahYfleHWwar/+5efUBkWWiznGk3T5Qt0vX4i1zugSv59Eg42KwftQw8lRqdS5I4lN5Bv7gLsV01blHNSFyg2m,iv:uptjZ+PD6c8IlttUYmqFoxj2mNMgGIjR1SlCRLnFSoo=,tag:Xv+GKrJeHKH642uw/Ju7nQ==,type:str]
kind: Secret
metadata:
    name: sops-age
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age140ydupaur7u5frpf2229zz73xwfg6ndpuwn27lna425y8t44ucfs07ahf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OGJVdk93aVRqTlN5dXRG
            WUVvQkhsNHljTXZNR3ZyMUpacENQdmVlVWlvCnV0UVB2QlRxZkxlYy8xcUZ4OHYr
            bmNLcHZpcVRQOW5IZWs3cFBaa3hkdHcKLS0tIFZOVzhzb3RiRVBmRVpkcnhoNlAv
            dXJIUzVvdjIrdDJVeHd5ekxpdnJFWW8KI8Xmohe3bXcafupsSV8oBgNyHly9df6E
            Ua5flRgK+wK5/7CyDUcp+mCVbZDt2SIivEeCIEKfsAKckDAlE8hy3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-15T18:31:06Z"
    mac: ENC[AES256_GCM,data:cD3MqKE5fDJJnTod6/dFc1KGemeybIrK/VERXxCLzUUNDvLmkcQTsjY5lpu0e55mDW9NCkTOSMxIF4acjJE4Wbm7V3Updwj7Z9zEyzRgt1jE086tCuueaRSyDRa0fmOYwP5F63fyftA3antSnMIpb7sgdtVRTYmYEB5QJevymCc=,iv:w4Dm4wmPt5N0lYwhJYH+y5yjvoZqRmy5iZ7Fg+zWXtw=,tag:SFHmgVU39chK4Zd2FR+PgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
