---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 5m
  timeout: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.4.1
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      reclaimPolicy: Delete
      recurringJobSelector:
        enable: false
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns/is-public: "true"
        #nginx.ingress.kubernetes.io/auth-url: http://authelia.networking.svc.cluster.local/api/verify
        #nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}
      host: longhorn.${SECRET_DOMAIN}
    defaultSettings:
      storageOverProvisioningPercentage: 100
      storageMinimalAvailablePercentage: 10
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      restoreVolumeRecurringJobs: true
      defaultLonghornStaticStorageClass: longhorn-backup
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      orphanAutoDeletion: true