---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  path: ./base/staging
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client